apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 80
    nodePort: 30088
  selector:
    app: backend
  type: NodePort
status:
  loadBalancer: {}
